import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./Providers";
import Nav from "@/components/nav";
import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "700"] });

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <Providers>
                    <main
                        className={cn(
                            poppins.className,
                            "relative mx-auto flex max-h-screen min-h-screen max-w-2xl flex-col items-center p-4",
                        )}
                    >
                        <div className="flex h-full w-full max-w-2xl flex-col">
                            <Nav />
                            <div className="mt-14 sm:mt-20">{children}</div>
                            <Footer />
                        </div>
                    </main>
                </Providers>
            </body>
        </html>
    );
}
