import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./Providers";
import Nav from "@/components/nav";
import "@fontsource/poppins";
import "@fontsource/raleway";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <main className="relative mt-5 flex max-h-screen min-h-screen flex-col items-center bg-primary dark:bg-zinc-950/40">
                        <div className="flex h-full w-full max-w-2xl flex-col">
                            <Nav />
                            <div className="mt-20 px-5">{children}</div>
                        </div>
                    </main>
                </Providers>
            </body>
        </html>
    );
}
